### PR TITLE
Strip unused functions and data

### PR DESCRIPTION
**Pull request by pexcn**
Commit by @wongsyrone: https://github.com/wongsyrone/lede-1/blame/master/package/external/shadowsocks-libev/Makefile#L71-L73

### CODE REVIEW

**Comment by wongsyrone** [comment]
Well, use this with caution. I am against adding this as default.

**Comment by pexcn** [comment]
Why?

**Comment by wongsyrone** [comment]
The behavior is not guaranteed.

**Comment by pexcn** [comment]
Should

**Comment by wongsyrone** [comment]
If someone has interest, he can try this himself, but it is not recommended to apply this to everyone.

**Pull request closed without merging**
